#!/bin/sh

### BEGIN INIT INFO
# Provides:             clue-splash
# Required-Start:       $all
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Stop/start splash application according to the system status
### END INIT INFO

############### EDIT ME ##################

NAME=clue-splash
DESC="Clue Splash"
DAEMON="/opt/clue/bin/splash"

############### END EDIT ME ##################

setup=n
splash=n

test -x $DAEMON || exit 0

RUNLEVEL=
if [ "${RUNLEVEL}" = "" -o "${RUNLEVEL}" = "unknown" ]; then RUNLEVEL=5 ; fi

. /lib/lsb/init-functions

for x in $(cat /proc/cmdline); do
	case $x in
		splash)
			splash=y
			;;
		setup)
			setup=y
			;;
	esac
done

case "$1" in
    start)
    	if [ "$setup" = "y" ] && [ -f /opt/clue/bin/setup ]; then
			if [ "$splash" = "y" ]; then
				/opt/clue/bin/setup --splash --init &
			else
				/opt/clue/bin/setup --init &
			fi
			sleep 3
		elif [ "$setup" != "y" ] && [ -f /opt/clue/bin/setup ]; then
    		if [ "$splash" = "y" ]; then
    			$DAEMON --message="starting services.." --ypoint=-34 --wipe
				if [ -f /etc/init.d/clue-mcpi ] && [ "$(/opt/clue/bin/setup -g service -b mcpi)" = "+" ] && [ "$(/sbin/runlevel | cut -d " " -f 2)" = "" ]; then
					$DAEMON --message="starting MCPi.." --ypoint=-34
					$DAEMON --exit=30
				fi
			fi
		fi
		;;
    stop)
    	if [ "$splash" = "y" ]; then
			$DAEMON --image=splash --console --reset
			$DAEMON --message="stopping services.." --ypoint=-34
			sleep 1
		fi
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
exit 0
