#!/bin/bash

if [ "$1" == "configure" ]; then
	# Register InitRamFS
	chmod +x /etc/initramfs-tools/hooks/splash
	chmod +x /etc/initramfs-tools/scripts/init-top/splash
	update-initramfs -u >/dev/null 2>&1

	# Register service
	chmod +x /etc/init.d/clue-splash
	/usr/sbin/update-rc.d clue-splash defaults >/dev/null 2>&1
	/bin/systemctl daemon-reload >/dev/null 2>&1
fi
