#!/bin/bash

if [ "$1" == "remove" ] || [ "$1" == "purge" ]; then
	# Update InitRAM FS
	update-initramfs -u > /dev/null 2>&1

	# Reload services controller
	/bin/systemctl daemon-reload >/dev/null 2>&1
fi